apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-leak-demo
  labels:
    app: memory-leak-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-leak-demo
  template:
    metadata:
      labels:
        app: memory-leak-demo
      annotations:
        ad.datadoghq.com/memory-leak-demo.logs: '[{"source": "java", "service": "memory-leak-demo"}]'
        ad.datadoghq.com/memory-leak-demo.check_names: ["openmetrics"]
        ad.datadoghq.com/memory-leak-demo.init_configs: [{}]
        ad.datadoghq.com/memory-leak-demo.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:8080/actuator/prometheus",
              "namespace": "springboot",
              "metrics": ["jvm_memory_used_bytes", "jvm_gc_pause_seconds_count"]
            }
          ]
    spec:
      containers:
      - name: memory-leak-demo
        image: your-dockerhub-user/memory-leak-demo:latest
        ports:
        - containerPort: 8080
        env:
        - name: DD_SERVICE
          value: "memory-leak-demo"
        - name: DD_ENV
          value: "lab"
        - name: DD_VERSION
          value: "1.0.0"
        - name: DD_LOGS_ENABLED
          value: "true"
        - name: DD_TRACE_ENABLED
          value: "true"
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
